server:
  port: 0

spring:
  application:
    name: velocura-backend-test
  datasource:
    url: jdbc:h2:mem:velocura_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: false

velocura:
  admin:
    email: admin@velocura.com
    password: testAdminPassword123!
  payment:
    mock-enabled: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 3600000
