package com.velocura.medicalknowledge.model;

/**
 * Enumeration of quarantine causes per Section 19.
 * Quarantined records must NEVER silently enter the authoritative knowledge snapshot.
 */
public enum QuarantineReason {
    MALFORMED_RECORD,
    MISSING_IDENTIFIER,
    INVALID_IDENTIFIER,
    INVALID_RELATIONSHIP,
    UNRESOLVED_ENTITY,
    AMBIGUOUS_ENTITY,
    AMBIGUOUS_MAPPING,
    INVALID_TERMINOLOGY_MAPPING,
    DUPLICATE_RECORD,
    DUPLICATE_CONFLICT,
    INVALID_UNITS,
    INVALID_UNIT,
    IMPOSSIBLE_VALUE,
    PHYSIOLOGICALLY_IMPOSSIBLE,
    UNSUPPORTED_SOURCE,
    LICENSE_REVIEW_REQUIRED,
    LICENSE_RESTRICTED,
    PROVENANCE_MISSING,
    MISSING_PROVENANCE,
    MISSING_JURISDICTION,
    SCHEMA_VIOLATION,
    MEDICAL_SEMANTIC_CONFLICT,
    CONFLICTING_RELATIONSHIP,
    PARSER_FAILURE,
    BROKEN_REFERENCE
}
