package com.velocura.medicalknowledge.model;

public enum RelationshipType {
    CAUSES,
    ASSOCIATED_WITH,
    HAS_SYMPTOM,
    HAS_SIGN,
    HAS_FINDING,
    HAS_RISK_FACTOR,
    RISK_FACTOR_FOR, // Backward compatibility
    HAS_COMPLICATION,
    COMPLICATION_OF, // Backward compatibility
    DIFFERENTIAL_OF,
    CONTRAINDICATED_IN,
    INTERACTS_WITH,
    DUPLICATE_OF,
    DUPLICATES, // Backward compatibility
    HAS_ACTIVE_INGREDIENT,
    HAS_LAB_ASSOCIATION,
    HAS_BIOMARKER,
    MONITORED_BY,
    TREATED_BY,
    ADVERSE_EFFECT,
    CAUSES_ADVERSE_EFFECT, // Backward compatibility
    ALLERGY_CONFLICT,
    ALLERGIC_TO, // Backward compatibility
    RELATED_ANATOMY,
    LOCATED_IN, // Backward compatibility
    PRECEDES,
    FOLLOWS,
    SUPPORTED_BY,
    RECOMMENDED_BY,
    MIMICS,
    INVESTIGATED_BY,
    CAUTION_IN,
    AFFECTS_LAB,
    REQUIRES_RENAL_ADJUSTMENT,
    CAUTION_IN_RENAL_IMPAIRMENT,
    CONTRAINDICATED_IN_RENAL_IMPAIRMENT,
    CAUTION_IN_HEPATIC_IMPAIRMENT,
    CONTRAINDICATED_IN_HEPATIC_IMPAIRMENT,
    EVALUATED_BY_LAB,
    ASSOCIATED_WITH_LAB_ABNORMALITY,
    SUBTYPE_OF,
    PART_OF,
    NARROWER,
    BROADER,
    MEMBER_OF_CLASS,
    OTHER
}

